### ISSUE TITLE
should text messages include backslash?

### ISSUE THREAD

**Issue by lucasfernandodev** [causaly/zod-validation-error#15]
I have two questions, the first is about the backslash, is it normal and should I remove it when sending it to the user? or is it some error.
And how to make responses from fields that use "or" less redundant?
For example:
```
export const novelSchema = z.object({
  id: z.string().uuid(),
  thumbnail: z.string(),
  title: z.string(),
  author: z.string().array().or(z.string()),
  genre: z.string().array().or(z.string()),
  state: z.string(),
  lastChapter: z.object({
    title: z.string(),
    timeago: z.string(),
  }),
  chapters: z.record(z.string().min(1), z.string()),
  url: z.string(),
});
```

if I don't pass the "author" field it returns:
```
"Validation error: Required at \"author\", or Required at \"author\""
```

**Comment by jmike** [comment]
The first question re:backslash is simple.

> I have two questions, the first is about the backslash, is it normal and should I remove it when sending it to the user? 

It's normal. You should NOT remove it when sending to the user. Here's why...

This is how JS escapes double quotation marks (i.e. `"`) inside a double-quoted string. If you render this on your browser or print it on the console the quotes will be automatically removed.

>  how to make responses from fields that use "or" less redundant?

This is a valid concern. We need to work on it and provide a fix. Please allow us some time or feel free to open a PR yourself.

**Comment by lucasfernandodev** [comment]
Thank you very much!

I'm starting to study zod now, but if I have any ideas I'd love to contribute.
