### ISSUE TITLE
deal with illegal property

### ISSUE THREAD

**Issue by tjx666** [causaly/zod-validation-error#18]
schema:

```javascript
const noneEmptyString = z.string().trim().min(1);
const relativePath = z.string().regex(/^\.\/[\d/a-z-]+?$/);
const containsEsmExport = z.object({
    import: z.union([
        noneEmptyString,
        z.object({
            default: relativePath,
        }),
    ]),
});

const packageJSONSchema = z.object({
    exports: z.object({
        '.': containsEsmExport,
        './*': containsEsmExport,
    }),
});
```

<img width="989" alt="image" src="https://user-images.githubusercontent.com/41773861/221954759-203ef76c-a79f-4dff-b48c-ec9c3b5d6ce6.png">

**Comment by jmike** [comment]
@tjx666 thank you for opening this issue.

Can you please provide clear instructions to replicate the aforementioned behaviour? In particular, we have the schema from the description of this issue - it would save us significant time if you also provided the input.

**Comment by tjx666** [comment]
@jmike 

```
{
    "exports": {
        ".": {
            "import": {
                "development": "./src",
                "default": "./dist/es"
            }
        },
        "./*": {
            "import": {
                "development": "./src/*",
                "default": "./dist/es/*"
            }
        }
    }
}
```

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/41773861/224788742-5cb9bd34-b62e-4b74-8fbb-7c616fcfd943.png">

**Comment by jmike** [comment]
Thank you for the explanation. Fix PR opened. Please wait a couple of days for approval. You are also welcome to review yourself.
