### ISSUE TITLE
Track the originating ZodError as `cause`

### ISSUE THREAD

**Issue by arty-name** [causaly/zod-validation-error#210]
The standard Error class now has a [standard property `cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause), and the support for it slowly spreads in the tools. 

I believe it would be nice to have the original `ZodError` to be available as the `cause` property of the `ValidationError`.

**Comment by jmike** [comment]
I agree, wanted to do this for a while. However it will result in a breaking change. Therefore, we need to bump the major version after the change has been implemented and approved.
