### ISSUE TITLE
Improve the docs example

### ISSUE THREAD

**Issue by davesierra** [causaly/zod-validation-error#218]
Hi, thanks for this package, definitely useful. The only feedback is that the docs seem a little confusing, given this example in the quickstart section:

```
const validationError = fromZodError(err);
  // the error now is readable by the user  
  // you may print it to console
  // or return it via an API
  console.log(validationError);
```

I tried to output `validationError` and expected to get the same output in the next section, a string simply: "Validation error: Number must be greater than 0 at "id"; Invalid email at "email"" but instead I got that message including the full error object, which contrary to what the comment says "the error now is readable by the user", is not what you would want to return (in my case). 

I spent 10 minutes looking into it to realize that `fromZodError` returns the `ValidationError` which includes the message and full error, and while it doesn't make full sense to me to include the error when you already can access it via the original Zod Error object as if you wanted to include it you can append it to each other, and include it if you wish.

Perhaps a suggestion to modify to this:
```
const validationError = fromZodError(err);
  // the full ValidationError object, including the human readable string and original error
  console.log(validationError);
  
  // use .message to output only the string readable by the user
  const humanReadableError = validationError.message
  //output: Validation error: Number must be greater than 0 at "id"; Invalid email at "email"
  console.log(humanReadableError );
```

Thanks for listening.

**Comment by jmike** [comment]
@davesierra this is how every Error instance works. Try the following...

```javascript
const err = new Error('foo', {cause: 'bar'});
console.log(err);
```

The output in the console contains the complete error.

Whereas is you do `console.log(err.toString());` you get an actual string.

In any case, I understand it might be confusing to some devs, so point taken. We will update the docs.

**Comment by jmike** [comment]
Closing this issue as the docs have been updated accordingly.
