### ISSUE TITLE
Cannot find name 'ErrorOptions'

### ISSUE THREAD

**Issue by CedericPrivat** [causaly/zod-validation-error#226]
I just updated to the lastest version of this library (3.0.0) and get the following error, when I create a build for a NodeJS/Express app:

```bash
node_modules/zod-validation-error/dist/types/ValidationError.d.ts:5:45 - error TS2304: Cannot find name 'ErrorOptions'.

5     constructor(message?: string, options?: ErrorOptions);
   
```

Am I missing something or is there in issue with the `ErrorOptions` typescript type missing?

I appreciate any help or direction you can provide.

**Comment by CedericPrivat** [comment]
I found the issue! For anyone having a similar issue, here is what fixed it:

In our [tsconfig.json](url) we specified the `lib` property to be `["ES6"]`,  which sets the bundled library declaration files that describe the target runtime environment.
Since the `ErrorOptions` type is only available in `es2022` and higher, we just needed to change the value to `["es2022"]`.

**Comment by jmike** [comment]
Thanks @CedericPrivat , maybe we could export custom error options from `zod-validation-error` to get around this problem. Unsure but worth exploring.
