### ISSUE TITLE
Validation Error Handler with Prisma Error

### ISSUE THREAD

**Issue by lutfiblog** [causaly/zod-validation-error#25]
I have this error message when using fromZodError(err)
`{
    "error": "Sorry something Happened! Cannot read properties of undefined (reading 'slice')"
}` 

the prisma error is comes from duplicate record, so the error should return like this
`
{
    "code": "P2002",
    "clientVersion": "4.11.0",
    "meta": {
        "target": [
            "email"
        ]
    }
}
`

How to check if the error coming from zodError or non zod error?

**Comment by jmike** [comment]
Hi @lutfiblog , thanks for opening this issue. I am not I follows what the problem is.

If you want to distinguish between a prisma error and a `ZodValidationError` then please use https://github.com/causaly/zod-validation-error#isvalidationerrorlike

If you are wrapping a Prisma error into a ZodValidationError then please provide a code snippet to better understand what you are doing and determine where the problem lies.

**Comment by jmike** [comment]
@lutfiblog does my answer above cover you? Please elaborate.

**Comment by lutfi-haslab** [comment]
Hello, sorry for my late response, i can flag this issue as solved.
this is how i solved the problem:
`
try {
    const data = User.parse({
      name: req.body.name,
      email: req.body.email,
    });

    const user = await prisma.user.create({
      data
    })

    res.status(200).json({
      user
    })
  } catch (err: any) {
    if (err.name == "ZodError") {
      const validationError = fromZodError(err);
      return res.json(String(validationError))
    }

    return res.json(err)
  }`

the problem was, i am using else

**Comment by lutfiblog** [comment]
Hello, sorry for my late response, i can flag this issue as solved.
this is how i solved the problem:
`
try {
    const data = User.parse({
      name: req.body.name,
      email: req.body.email,
    });

    const user = await prisma.user.create({
      data
    })

    res.status(200).json({
      user
    })
  } catch (err: any) {
    if (err.name == "ZodError") {
      const validationError = fromZodError(err);
      return res.json(String(validationError))
    }

    return res.json(err)
  }`

the problem was, i am using else
