### ISSUE TITLE
Why does this library rely on nodejs v18

### ISSUE THREAD

**Issue by Erchoc** [causaly/zod-validation-error#270]
hi, Why does this library rely on nodejs v18? 

Do I have any problems using nodejs v16?

**Comment by NoahAndrews** [comment]
It's probably just that they don't test against node.js 16 any more because it's no longer maintained (which should be enough reason for you to strongly consider moving away from it). See https://nodejs.org/en/about/previous-releases

**Comment by jmike** [comment]
Exactly what @NoahAndrews wrote above.
