### ISSUE TITLE
Global setting to customise all error messages 

### ISSUE THREAD

**Issue by ritz078** [causaly/zod-validation-error#35]
Is there a way to use this library in a way that all the errors are automatically formatted ?

I beleive there is a `setErrorMap` method that can be used but not sure if this library supports it. https://zod.dev/ERROR_HANDLING?id=customizing-errors-with-zoderrormap

**Comment by dimitrisnl** [comment]
Hey there. Based on this snippet from the docs

```ts
import { z } from "zod";

const customErrorMap: z.ZodErrorMap = (issue, ctx) => {
  if (issue.code === z.ZodIssueCode.invalid_type) {
    if (issue.expected === "string") {
      return { message: "bad type!" };
    }
  }
  if (issue.code === z.ZodIssueCode.custom) {
    return { message: `less-than-${(issue.params || {}).minimum}` };
  }
  return { message: ctx.defaultError };
};

z.setErrorMap(customErrorMap);
```

it's my understanding that Zod will prioritize your custom error map, and override its default message.

Now everything `zod-validation-error` does, comes after that. So your formatted message will be already updated.
Let me know if I'm missing something obvious, but I don't see any conflict.

**Comment by faner11** [comment]
I'm really looking forward to supporting setErrorMap, because currently zod is very difficult to customize errors in forms and support other languages, currently only zod-i18n-map, but this is something we don't need i18n for.

**Comment by OriginalEXE** [comment]
+1 for having a way to apply this either to a specific schema, or globally, so it's useable with libraries like `https://www.remix-validated-form.io/reference/validated-form`

**Comment by jmike** [comment]
It's not clear to me what the solution for this issue should be. The team is happy to accommodate your request, but you need to make it more concrete for us to understand what we need to do.

@dimitrisnl provided a workaround that doesn't require exposing an additional API at `zod-validation-error` level.

Is this not sufficient? If so, what is the request? Can you provide an example in pseudocode?

**Comment by seo-ai-team** [comment]
> It's not clear to me what the solution for this issue should be. The team is happy to accommodate your request, but you need to make it more concrete for us to understand what we need to do.
> 
> @dimitrisnl provided a workaround that doesn't require exposing an additional API at `zod-validation-error` level.
> 
> Is this not sufficient? If so, what is the request? Can you provide an example in pseudocode?

We're looking to globally apply zod-validation-error instead of needing to remember to apply it every time. In the "workaround" mentioned, it's impossible to call zod-validation-error inside of a customErrorMap.

CustomErrorMap gives you Zod.issues while zod-validation-error requires you to pass in a Zod.Error

We're looking for something like this:
`
const customErrorMap: z.ZodErrorMap = (issue, ctx) => {
  return { message: fromZodError(ctx.issue) };
};
`
so that we can 
`
z.setErrorMap(customErrorMap)
`

**Comment by jmike** [comment]
@seo-ai-team awesome, this helps a lot. We'll get back to you with more details.

**Comment by OriginalEXE** [comment]
@seo-ai-team put it well, this would enable compatibility with libraries that don't expose Zod error directly, but use it under the hood to display errors (like the library I referenced). Thanks for considering it!

**Comment by jmike** [comment]
The latest version (v.1.4.0) of `zod-validation-error` features a new `fromZodIssue` method that allows you to create a `ValidationError` from a single zod issue (instead of a zod error). You may use this function to power the customErrorMap use-case.

For further info please read...
https://github.com/causaly/zod-validation-error#fromzodissue

cc/ @seo-ai-team @OriginalEXE @ritz078 @faner11

**Comment by OriginalEXE** [comment]
Thank you very much for that, works great! One struggle I've had is that `setErrorMap` passes `z.ZodIssueOptionalMessage` which means `message` could be `undefined`. Easily solvable though:

```
z.setErrorMap((issue, context) => {
  const error = fromZodIssue({
    ...issue,
    message: issue.message ?? context.defaultError,
  });

  return {
    message: error.message,
  };
});
```

Thanks again ❤️

**Comment by jmike** [comment]
I am not sure if the `fromZodIssue()` function should accept `ZodIssueOptionalMessage`. We could certainly do that and call the `defaultErrorMap` internally to produce a message for error types that have no message. @nikoskalogridis what say you?

I think that if you set a custom `ErrorMap` you are also responsible for mapping each error type to an error message of your preference. Zod makes this easy by providing the default error message as `ctx.defaultError` - see https://zod.dev/ERROR_HANDLING?id=customizing-errors-with-zoderrormap.

Therefore, although I do not have a strong preference, I lean towards leaving it as-is.

@OriginalEXE this is the way 🙇

**Comment by jmike** [comment]
OK, last try - I 've opened another PR that should cover this use-case sufficiently.

https://github.com/causaly/zod-validation-error/pull/58

**Comment by nikoskalogridis** [comment]
> I think that if you set a custom `ErrorMap` you are also responsible for mapping each error type to an error message of your preference. Zod makes this easy by providing the default error message as `ctx.defaultError` - see https://zod.dev/ERROR_HANDLING?id=customizing-errors-with-zoderrormap.

I am also leaning on leaving it as-is. Since it can already be handled as you mention above I prefer to have thinner api
