### ISSUE TITLE
Provide a message builder option

### ISSUE THREAD

**Issue by BioPhoton** [causaly/zod-validation-error#357]
Thanks for the great lib front off! Really well documented and structured.

# Motivation

As a developer I want to have full control of the created error message. 
Examples of what I want to control is:
- all data displayed in the message (e.g. apply different pathoining)
- text of the displayed message
- font style of the message (for terminal usage)

# Acceptance criteria

- [ ] implement a `messageBuilder(issue: ZodIssue): string` option so I can have full control of the error.

**Comment by jmike** [comment]
Yes, that is a good suggestion that would also address https://github.com/causaly/zod-validation-error/issues/311

I cannot commit on a delivery time, but I would like to work on it.

**Comment by jmike** [comment]
@BioPhoton would you be so kind as to review the PR that implements `MessageBuilder` here (https://github.com/causaly/zod-validation-error/pull/363)?

If you don't are unable to go through the code, then at least read the docs and let us know if this is what you also had in mind.

**Comment by jmike** [comment]
I expect the new `MessageBuilder` to land on npm on the week of Sep 16 (early). Stay tuned.
