### ISSUE TITLE
[Help] How I can I use this library along with React-hook-form

### ISSUE THREAD

**Issue by Aniket-IN** [causaly/zod-validation-error#36]
Hi, 

First of all, thank you so much for the amazing library. 
I'm new to Zod, and trying to implement `zod-validation-error` along with `react-hook-form` .

Currently I'm using Zod schema and `zodResolver` to connect with `react-hook-form`, like this:
But not sure, how do I implement this library, 
```js
  const schema = z.object({
    contact_name: z.string().min(3),
    email: z.string(),
    alt_email: z.string(),
    phone_country_code: z.string(),
    phone: z.string(),
    alt_phone_country_code: z.string(),
    alt_phone: z.string(),
  });

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<LeadFormInputs>({
    resolver: zodResolver(schema), // Here's the resolver
  });
```

**Comment by dimitrisnl** [comment]
Hey @Aniket-IN - sorry for the delay. 

Can you tell me what are you trying to achieve in more detail?
I'm not well versed in `react-hook-form`, but it's my understanding that the errors are well formatted out of the box.

See the attached sandbox https://codesandbox.io/s/amazing-lehmann-wg9mxo?file=/src/App.tsx

**Comment by xsjcTony** [comment]
I think he's referring that react-hook-form resolves zod validation under the hood, where we are not able to get `ZodError` object, hence there's no way to use this library with it. Any suggestion?

**Comment by SamLeatherdale** [comment]
You can pass the error map function to the zodResolver:

```js
import { zodResolver } from '@hookform/resolvers/zod'
import { errorMap } from 'zod-validation-error'

useForm({
  resolver: zodResolver(schema, { errorMap })
})
```

**Comment by jmike** [comment]
Closing this issue given that the question has been answered by @SamLeatherdale (thank you 🙇 ).
