### ISSUE TITLE
Type checking failing due to exported types

### ISSUE THREAD

**Issue by Samuel-West** [causaly/zod-validation-error#96]
First of all - thanks for the library, really useful.

I'm getting an interesting error when running a type-check job in our project (via `tsc -p`):

`/node_modules/zod-validation-error/dist/types/index.d.ts(1,121): error TS1005: ',' expected.`

We've not had this from any other dependency but it stems from the export syntax in this file - `export { type Foo }`. 

Is this due to the recent version of TS this library uses? We are currently on TS version 4.3, currently updating to 4.9.

Node shouldn't be an issue as we are on v18.

Let me know if I can provide anything else that would help!

**Comment by Samuel-West** [comment]
Resolved now - this syntax was introduced in TS 4.5

**Comment by jmike** [comment]
@thanoskrg @nikoskalogridis should we list `typescript v.4.5` as a min requirement in the docs?

**Comment by thanoskrg** [comment]
> @thanoskrg @nikoskalogridis should we list `typescript v.4.5` as a min requirement in the docs?

Yes @jmike , I think that would make sense 👍
